### ISSUE TITLE
wont add to watch list

### ISSUE THREAD

**Issue by marbysneaker** [Snivyn/ebay-watcher#1]
Couldn't add https://www.ebay.com/itm/273638546338 to watch list.
keep getting that message when i run the script
Did everything on the turorial including adding my own domain ( with catch-all, got all the emails from made accounts)
Adding my proxies under proxies.txt

**Comment by ghost** [comment]
> 
> 
> Couldn't add https://www.ebay.com/itm/273638546338 to watch list.
> keep getting that message when i run the script
> Did everything on the turorial including adding my own domain ( with catch-all, got all the emails from made accounts)
> Adding my proxies under proxies.txt

just replace "ebay.com" to "ebay.ca" in your link

**Comment by marbysneaker** [comment]
Wow got it thanx! It worked!
