### ISSUE TITLE
Cant get it working

### ISSUE THREAD

**Issue by Christian1998** [Snivyn/ebay-watcher#5]
What link do you want to watch: https://www.ebay.ca/itm/283116687683
Traceback (most recent call last):
  File "ebay-watcher.py", line 237, in <module>
    in_link = input("What link do you want to watch: ").strip()
  File "<string>", line 1
    https://www.ebay.ca/itm/283116687683
         ^
SyntaxError: invalid syntax

Anyone knows a solution?

**Comment by skycorrigan** [comment]
What was the solution that you found @Christian1998? I'm stuck at the same point?
